### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by appgurueu** [TheAlgorithms/Lua#1]
A few conventions (and ideally, matching GitHub CI actions) are needed:

1. Which formatter / formatting convention should be used? (I'm fairly biased as I've written my own)
2. What about documentation? (LuaDoc / LDoc?)
3. What about unit tests / testing? (probably busted)
4. Which Lua version should be targeted? (I suggest Lua 5.1)

**Comment by dhruvmanila** [comment]
I'm not that familiar with the lua ecosystem but here are my recommendations:

1. Stylua
2. Any works
3. Busted
4. LuaJIT/Lua 5.1

**Comment by appgurueu** [comment]
Alright, agreed on [StyLua](https://github.com/JohnnyMorganz/StyLua), busted and Lua 5.1. That leaves only the documentation tool to be decided.

**Comment by appgurueu** [comment]
LuaJIT / Lua 5.1 is target as Lua version.
