### ISSUE TITLE
Consider adding Lua to Hacktoberfest?

### ISSUE THREAD

**Issue by lynnpepin** [TheAlgorithms/Lua#3]
Hi! I am wondering if you would consider adding the Lua repo to Hacktoberfest, like many of the other repos under TheAlgorithms.

Recently I heard of Hacktoberfest, and I would be joyed to participate. I’ve been meaning to brush-up on my algorithms, and to learn Lua, so I’d expect I can happily contribute here. I believe I can’t be alone here, either!

**Comment by appgurueu** [comment]
I'd be fine with a test run. Unfortunately I don't think that I have sufficient permissions on the repository. @Panquesito7 could you do it?

**Comment by Panquesito7** [comment]
Great suggestion, thank you! I've added the `hacktoberfest` topic. 🚀
